openapi: 3.0.0
info:
  title: API
  version: 1.0.0
paths:
  /user:
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: '<img src=x onerror=alert(1)>'
