swagger: '2.0'
info:
  title: WAS API 
  description: |
    <img src/onerror=alert(1)>

  version: production
basePath: /WAS/
produces:
  - application/xml
  - application/json
consumes:
  - application/xml
  - application/json
security:
  - basicAuth: []
paths:
  /vulns:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - vulns
      operationId: findVulns
      summary: Find vulns
